name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - run: sudo apt-get install libasound2-dev
      - name: build kira
        run: cargo build -p kira
      - name: build kira-cpal
        run: cargo build -p kira-cpal
      - name: build kira-cpal with assert-no-alloc feature
        run: cargo build -p kira-cpal --features assert_no_alloc
      - name: build kira-loaders
        run: cargo build -p kira-loaders
      - name: build kira-examples
        run: cargo build --examples 
      - name: run tests
        run: cargo test
      - name: lint
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
